name: example_firebase_admin_frog
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_firebase_admin:
    git:
        url: https://github.com/akaboshinit/dart_firebase_admin.git
        path: packages/dart_firebase_admin
        ref: v0.0.0-20231119
  dart_frog: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
